"""
This type stub file was generated by pyright.
"""

"""
Exports function list_versions() for unicode version level support.

This code generated by bin/update-tables.py on 2020-06-23 16:03:21.350604.
"""
def list_versions():
    """
    Return Unicode version levels supported by this module release.

    Any of the version strings returned may be used as keyword argument
    ``unicode_version`` to the ``wcwidth()`` family of functions.

    :returns: Supported Unicode version numbers in ascending sorted order.
    :rtype: list[str]
    """
    ...

